### ISSUE TITLE
ERROR: command not found: when I run foreman run command

### ISSUE THREAD

**Issue by Kentverger** [mxabierto/datatron#3]
Hello, I executed `bundle install`, then `mongodb &` finally `foreman run` and I get the follow message: 
`ERROR: command not found:`

I have installed Ruby 2.0.0 over Ubuntu 15.04

**Comment by rodowi** [comment]
foreman is not included in the Gemfile because it's a global cli tool

**Comment by rodowi** [comment]
so you should installed it, I'm adding this to the README
